/**
 * Maps Material Symbols names (used as `<Icon name="…" />`) to Bootstrap Icons
 * SVG basenames (no .svg). Library: https://github.com/twbs/icons (MIT).
 */
export const MATERIAL_TO_BOOTSTRAP = {
  account_balance: 'bank',
  account_circle: 'person-circle',
  add: 'plus-lg',
  admin_panel_settings: 'shield-lock',
  alternate_email: 'at',
  android: 'google-play',
  arrow_back: 'arrow-left',
  arrow_forward: 'arrow-right',
  arrow_upward: 'arrow-up',
  auto_awesome: 'stars',
  accessibility: 'universal-access-circle',
  bookmark: 'bookmark-fill',
  bookmark_border: 'bookmark',
  calendar_month: 'calendar-month',
  calendar_today: 'calendar-day',
  celebration: 'balloon-fill',
  chat: 'chat-dots-fill',
  chat_bubble_outline: 'chat',
  check: 'check-lg',
  check_circle: 'check-circle-fill',
  chevron_left: 'chevron-left',
  chevron_right: 'chevron-right',
  close: 'x-lg',
  confirmation_number: 'ticket-perforated',
  content_copy: 'clipboard',
  delete: 'trash',
  directions_car: 'car-front-fill',
  directions_walk: 'person-walking',
  dynamic_feed: 'rss',
  edit: 'pencil-square',
  error: 'exclamation-triangle-fill',
  error_outline: 'exclamation-circle',
  event: 'calendar-event-fill',
  event_note: 'journal-text',
  explore: 'compass',
  expand_less: 'chevron-up',
  expand_more: 'chevron-down',
  family_restroom: 'people-fill',
  favorite: 'heart-fill',
  favorite_border: 'heart',
  filter_list: 'funnel',
  fit_screen: 'arrows-fullscreen',
  grid_view: 'grid-3x3-gap-fill',
  hiking: 'tree',
  hourglass_empty: 'hourglass-split',
  key: 'key-fill',
  keyboard_arrow_down: 'chevron-down',
  keyboard_arrow_up: 'chevron-up',
  link: 'link-45deg',
  list: 'list-ul',
  location_city: 'buildings',
  location_on: 'geo-alt-fill',
  lock: 'lock-fill',
  logout: 'box-arrow-right',
  mail: 'envelope',
  map: 'map',
  mark_email_read: 'envelope-check',
  movie: 'film',
  mosque: 'moon-stars-fill',
  more_horiz: 'three-dots',
  more_vert: 'three-dots-vertical',
  museum: 'bank',
  my_location: 'crosshair',
  navigation: 'compass-fill',
  open_in_new: 'box-arrow-up-right',
  payments: 'cash-coin',
  person: 'person-fill',
  person_add: 'person-plus-fill',
  phone_iphone: 'phone',
  photo_camera: 'camera-fill',
  photo_library: 'images',
  pin_drop: 'pin-map-fill',
  place: 'geo-alt',
  play_circle: 'play-circle-fill',
  print: 'printer',
  psychology: 'lightning-charge',
  radio_button_unchecked: 'circle',
  rate_review: 'chat-left-text-fill',
  remove: 'dash-lg',
  remove_circle_outline: 'dash-circle',
  reply: 'reply',
  restaurant: 'cup-hot-fill',
  route: 'diagram-3',
  schedule: 'clock',
  search: 'search',
  sell: 'tag-fill',
  send: 'send-fill',
  share: 'share',
  smartphone: 'phone-fill',
  star: 'star-fill',
  storefront: 'shop',
  touch_app: 'hand-index',
  travel_explore: 'globe2',
  trip_origin: 'signpost-fill',
  tune: 'sliders',
  verified: 'patch-check-fill',
  verified_user: 'shield-check',
  vertical_align_top: 'arrow-bar-up',
  view_list: 'list-task',
  visibility: 'eye',
  visibility_off: 'eye-slash',
  volume_off: 'volume-mute-fill',
  volume_up: 'volume-up-fill',
  waves: 'water',
};

/**
 * @param {string} materialName
 * @returns {string} Bootstrap icon file basename (kebab-case)
 */
export function getBootstrapIconSlug(materialName) {
  if (!materialName) return 'question-circle';
  const mapped = MATERIAL_TO_BOOTSTRAP[materialName];
  if (mapped) return mapped;
  return String(materialName).replace(/_/g, '-');
}
