/**
 * Material-style `Icon` `name` → Feather SVG basename in `/public/feather/{slug}.svg`.
 * @see https://feathericons.com/
 */

/** @type {Record<string, string>} */
export const MATERIAL_TO_FEATHER = {
  account_balance: 'layers',
  account_circle: 'user',
  add: 'plus',
  admin_panel_settings: 'settings',
  alternate_email: 'at-sign',
  android: 'smartphone',
  arrow_back: 'arrow-left',
  arrow_forward: 'arrow-right',
  arrow_upward: 'arrow-up',
  auto_awesome: 'zap',
  accessibility: 'life-buoy',
  bookmark: 'bookmark',
  bookmark_border: 'bookmark',
  calendar_month: 'calendar',
  calendar_today: 'calendar',
  celebration: 'gift',
  chat: 'message-square',
  chat_bubble_outline: 'message-circle',
  check: 'check',
  check_circle: 'check-circle',
  chevron_left: 'chevron-left',
  chevron_right: 'chevron-right',
  close: 'x',
  confirmation_number: 'hash',
  content_copy: 'copy',
  delete: 'trash-2',
  directions_car: 'truck',
  directions_walk: 'activity',
  dynamic_feed: 'rss',
  edit: 'edit-2',
  error: 'alert-circle',
  error_outline: 'alert-circle',
  event: 'calendar',
  event_note: 'calendar',
  explore: 'compass',
  expand_less: 'chevron-up',
  expand_more: 'chevron-down',
  family_restroom: 'users',
  favorite: 'heart',
  favorite_border: 'heart',
  filter_list: 'filter',
  fit_screen: 'maximize-2',
  grid_view: 'grid',
  hiking: 'trending-up',
  hotel: 'home',
  hourglass_empty: 'watch',
  key: 'key',
  keyboard_arrow_down: 'chevron-down',
  keyboard_arrow_up: 'chevron-up',
  link: 'link',
  list: 'list',
  location_city: 'home',
  location_on: 'map-pin',
  lock: 'lock',
  logout: 'log-out',
  mail: 'mail',
  map: 'map',
  mark_email_read: 'inbox',
  movie: 'film',
  mosque: 'home',
  more_horiz: 'more-horizontal',
  more_vert: 'more-vertical',
  museum: 'archive',
  my_location: 'crosshair',
  navigation: 'navigation-2',
  open_in_new: 'external-link',
  payments: 'credit-card',
  person: 'user',
  person_add: 'user-plus',
  phone_iphone: 'smartphone',
  photo_camera: 'camera',
  photo_library: 'image',
  pin_drop: 'map-pin',
  place: 'map-pin',
  play_circle: 'play-circle',
  print: 'printer',
  psychology: 'cpu',
  radio_button_unchecked: 'circle',
  rate_review: 'message-square',
  remove: 'minus',
  remove_circle_outline: 'x-circle',
  reply: 'corner-up-left',
  restaurant: 'coffee',
  route: 'git-branch',
  schedule: 'clock',
  search: 'search',
  sell: 'tag',
  send: 'send',
  share: 'share-2',
  smartphone: 'smartphone',
  star: 'star',
  storefront: 'shopping-bag',
  touch_app: 'zap',
  travel_explore: 'compass',
  trip_origin: 'flag',
  thumb_up: 'thumbs-up',
  thumb_down: 'thumbs-down',
  tune: 'sliders',
  verified: 'check-circle',
  verified_user: 'shield',
  vertical_align_top: 'chevron-up',
  view_list: 'list',
  visibility: 'eye',
  visibility_off: 'eye-off',
  volume_off: 'volume-x',
  volume_up: 'volume-2',
  waves: 'wind',
};

const FALLBACK = 'help-circle';

/**
 * @param {string} name Material-style icon key (`arrow_back`, `favorite_border`, …)
 * @returns {string} Feather file basename without `.svg`
 */
export function getFeatherSlug(name) {
  const key = name != null ? String(name).trim() : '';
  if (!key) return FALLBACK;
  if (MATERIAL_TO_FEATHER[key]) return MATERIAL_TO_FEATHER[key];
  const kebab = key.replace(/_/g, '-');
  if (/^[a-z0-9]+(-[a-z0-9]+)*$/.test(kebab)) return kebab;
  return FALLBACK;
}
