-- Tripoli Explorer — full heritage reset (places + categories)
-- Source: supplied Tripoli heritage guide (introduction, sites by type).
-- WARNING: Deletes ALL saved place rows and ALL places, then replaces categories.
-- Trip itineraries (trips.days) may still contain old place IDs until users edit them.
-- (No BEGIN/COMMIT: run-migrations.js wraps this file in a transaction.)

DELETE FROM saved_places;
DELETE FROM user_favourites;

-- Orphan FK-free references so DELETE places never fails on dangling links
UPDATE feed_posts SET place_id = NULL WHERE place_id IS NOT NULL;
UPDATE events SET place_id = NULL WHERE place_id IS NOT NULL;

DELETE FROM place_translations;
DELETE FROM places;

DELETE FROM category_translations;
DELETE FROM categories;

INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'heritage_overview',
  'Tripoli overview & history',
  'fas fa-book-open',
  'City introduction and deep historical narrative for visitors.',
  '["history","heritage","culture","tripoli","introduction","guide"]'::jsonb,
  0,
  '#1a5f7a'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'castles_towers',
  'Castles & towers',
  'fas fa-chess-rook',
  'Citadels and military towers from Crusader, Mamluk and later periods.',
  '["castle","citadel","fort","tower","crusader","mamluk","history","heritage","landmark"]'::jsonb,
  0,
  '#6B4423'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'mosques',
  'Historic mosques',
  'fas fa-mosque',
  'Mamluk and Ottoman mosques across the old city and river quarters.',
  '["mosque","mamluk","islamic","prayer","minaret","religious","history"]'::jsonb,
  0,
  '#1e5631'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'madrasas',
  'Madrasas',
  'fas fa-school',
  'Islamic colleges and Quranic schools.',
  '["madrasa","school","mamluk","islamic","education","heritage"]'::jsonb,
  0,
  '#3d5a80'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'khanqahs_takiyas',
  'Khanqahs & takiyas',
  'fas fa-archway',
  'Sufi lodges, khanqahs and the Mawlawi takiya.',
  '["sufi","khanqah","takiya","religious","heritage","dervish"]'::jsonb,
  0,
  '#5c4d7d'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'khans',
  'Khans (caravanserais)',
  'fas fa-warehouse',
  'Historic merchant inns and covered trade buildings.',
  '["khan","caravanserai","market","souk","shopping","historic","trade","souq"]'::jsonb,
  0,
  '#8B4513'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'hammams',
  'Hammams',
  'fas fa-bath',
  'Traditional public bathhouses, Mamluk and Ottoman.',
  '["hammam","bath","ottoman","mamluk","heritage"]'::jsonb,
  0,
  '#5d4e37'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'old_markets',
  'Historic markets',
  'fas fa-store',
  'Old souks and market quarters still in use.',
  '["souk","market","shopping","bazaar","old city","traditional"]'::jsonb,
  0,
  '#b45309'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'churches',
  'Churches & shrines',
  'fas fa-church',
  'Christian churches and shrines from Crusader era to 19th century.',
  '["church","christian","orthodox","cathedral","crusader","heritage"]'::jsonb,
  0,
  '#4a5568'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'modern_heritage',
  'Modern Tripoli landmarks',
  'fas fa-train',
  '19th–20th century stations, clock tower and Al-Tal square.',
  '["train","station","clock","square","ottoman","heritage","tal"]'::jsonb,
  0,
  '#2c5282'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'natural_urban',
  'Nature & major sites',
  'fas fa-water',
  'River, offshore islands, and the international fairgrounds.',
  '["river","island","sea","nature","fair","niemeyer","coast","mina","outdoors","water"]'::jsonb,
  0,
  '#0c5c59'
);
INSERT INTO categories (id, name, icon, description, tags, count, color) VALUES (
  'living_heritage',
  'Cuisine & crafts',
  'fas fa-utensils',
  'Tripolitan food culture and artisanal handicraft traditions.',
  '["food","cuisine","sweets","craft","handicraft","tradition","restaurant"]'::jsonb,
  0,
  '#c05621'
);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

INSERT INTO places (id, name, description, location, latitude, longitude, search_name, images, category, category_id, duration, price, best_time, rating, review_count, hours, tags, checkin_token) VALUES
(
  'tripoli_introduction',
  'Tripoli — introduction',
  'The second-largest city in Lebanon and capital of North Lebanon, Tripoli lies about 85 km north of Beirut. It is a welcoming city where history and the present coexist, with a lively economy and a calm rhythm of life. The city holds numerous historical and archaeological buildings — over forty listed as heritage — including mosques, schools, caravanserais and public baths, most from the Mamluk period, especially the 14th century AD. Its markets and caravanserais group artisans by trade — soap makers, goldsmiths, herbalists, tanners, tailors and more — forming urban quarters that still carry medieval character.',
  'Tripoli, North Lebanon',
  34.4347,
  35.8365,
  NULL,
  '[]'::jsonb,
  'Tripoli overview & history',
  'heritage_overview',
  '15–30 mins read',
  '',
  'Any time',
  NULL,
  NULL,
  NULL,
  '["tripoli","lebanon","introduction","heritage","mamluk","souks"]'::jsonb,
  encode(digest('tripoli_introduction', 'sha256'), 'hex')
),
(
  'tripoli_journey_history',
  'A journey into Tripoli’s history',
  'Historical records show Tripoli existed by the 14th century BC; the city was once called Wahliya in Tell el-Amarna letters, on what is now Abou Samra Hill. By the 9th century BC Phoenicians built a trading post on the peninsula of El-Mina; it became a federal hub in the Persian era. Tripoli commanded key military and commercial crossroads: the Akkar gateway, two natural harbours and offshore islets. Under Alexander’s successors it remained an important naval station; Roman rule brought grand public buildings — temples such as Baal (possibly under today’s Taynal Mosque) and Astarte appear on coinage, and inscriptions describe games in its stadium. A severe earthquake and tsunami struck in 551 AD. After the Islamic conquest (after 635 AD) Tripoli served the Umayyad navy; under Fatimid judges of the Banu Ammar in the mid-11th century it gained autonomy as a centre of science and culture. In 1109 the Crusaders besieged and captured the city, destroying much of its fabric. Later periods restored maritime and cultural prominence.',
  'Historical overview — Tripoli',
  34.436,
  35.838,
  NULL,
  '[]'::jsonb,
  'Tripoli overview & history',
  'heritage_overview',
  '30–45 mins read',
  '',
  'Any time',
  NULL,
  NULL,
  NULL,
  '["history","phoenician","roman","crusader","islamic","fatimid"]'::jsonb,
  encode(digest('tripoli_journey_history', 'sha256'), 'hex')
),
(
  'tripoli_citadel_saint_gilles',
  'Tripoli Castle (Citadel of Saint-Gilles)',
  'Known in the Crusader era as Tallat el-Hajjaj, on the summit of Abi Samra. Established in 645 by the Arab commander Sufyan al-Azdi, rebuilt by Count Raymond de Saint-Gilles, and restored by Prince Asandamir al-Korji after the Mamluks burned it in 1289; it has been renovated many times. The citadel has a main gate in the first tower and two smaller gates under the 12th and 22nd towers; openings lead to stairs down to underground levels used as prisons, arms stores and catacombs linked to surrounding houses and coastal towers.',
  'Abi Samra hill, Tripoli',
  34.4562,
  35.8431,
  NULL,
  '[]'::jsonb,
  'Castles & towers',
  'castles_towers',
  '1–2 hours',
  '',
  'Morning or late afternoon',
  4.7,
  0,
  NULL,
  '["citadel","crusader","mamluk","fortress","castle"]'::jsonb,
  encode(digest('tripoli_citadel_saint_gilles', 'sha256'), 'hex')
),
(
  'barsbay_tower',
  'Barsbay Tower (Lion Tower)',
  'Built in the mid-14th century by Prince Sayf al-Din Barsbay bin Abdullah bin Hamza al-Nasiri; also called the Lion Tower. A notable example of Mamluk military architecture.',
  'Tripoli waterfront / port area',
  34.451,
  35.81,
  NULL,
  '[]'::jsonb,
  'Castles & towers',
  'castles_towers',
  '30–45 mins',
  '',
  'Daylight',
  NULL,
  NULL,
  NULL,
  '["tower","mamluk","military","port"]'::jsonb,
  encode(digest('barsbay_tower', 'sha256'), 'hex')
),
(
  'great_mansouri_mosque',
  'Great al-Mansouri Mosque',
  'The oldest mosque in Tripoli and the first built in the Mamluk era — a major landmark. Sultan al-Ashraf Khalil bin Qalawun built it in 1294 on the ruins of an old church; Sultan al-Nasir Muhammad bin Qalawun added the arcades around the outer courtyard in 1315. It covers about 3,224 m². The four-storey minaret is in Italian Lombard style; the wooden minbar retains fine geometric decoration.',
  'Old city — al-Nouri quarter area',
  34.4341,
  35.8354,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '45 mins – 1 hour',
  '',
  'Between prayer times',
  4.8,
  0,
  NULL,
  '["mosque","mamluk","minaret","great mosque"]'::jsonb,
  encode(digest('great_mansouri_mosque', 'sha256'), 'hex')
),
(
  'sidi_abd_al_wahed_meknasi_mosque',
  'Mosque of Sidi Abd al-Wahed al-Meknasi',
  'Built in 1306 by Sheikh Abd al-Wahed al-Meknasi, a Moroccan imam — among Tripoli’s oldest Mamluk mosques. Noted for Moroccan architectural influence and one of the smallest minarets among the old city’s mosques.',
  'Old city, Tripoli',
  34.4335,
  35.8346,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '20–30 mins',
  '',
  'Between prayer times',
  NULL,
  NULL,
  NULL,
  '["mosque","mamluk","moroccan"]'::jsonb,
  encode(digest('sidi_abd_al_wahed_meknasi_mosque', 'sha256'), 'hex')
),
(
  'al_burtasi_mosque_madrasa',
  'Al-Burtasi Mosque and Madrasa',
  'Built in the 14th century by Issa bin Omar al-Burtasi; functioned as a law school linked to the Shafi’i school. On the bank of the Abou Ali River; praised as a masterpiece mixing Byzantine, Fatimid and Andalusian influences, with an arched minaret. Popular with European travellers in the 19th century.',
  'Abou Ali River bank, old city',
  34.4329,
  35.8324,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '30–45 mins',
  '',
  'Daylight',
  NULL,
  NULL,
  NULL,
  '["mosque","madrasa","river","mamluk"]'::jsonb,
  encode(digest('al_burtasi_mosque_madrasa', 'sha256'), 'hex')
),
(
  'al_tawba_mosque',
  'Al-Tawba Mosque (Mosque of Repentance)',
  'Built in the 14th century under Sultan al-Nasir Qalawun. Tradition holds it was founded as repentance after the architect of the Great Mansouri Mosque was found to have embezzled funds from that project. On the Abou Ali River; noted for a bronze plaque marking the 1643 flood, and a handsome dome and hexagonal minaret.',
  'Abou Ali River bank',
  34.4332,
  35.8328,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '30 mins',
  '',
  'Between prayer times',
  NULL,
  NULL,
  NULL,
  '["mosque","river","mamluk"]'::jsonb,
  encode(digest('al_tawba_mosque', 'sha256'), 'hex')
),
(
  'al_attar_mosque',
  'Al-Attar Mosque',
  'Built in 1334 by Badr al-Din al-Attar on a Crusader church foundation. North of Khan al-Masriyin (Egyptians’ Khan). It has Tripoli’s tallest minaret — square and unusually ornate, like a military tower. Three gates: north to the new market, west named for its builder-engraver, east with geometric patterns and historic inscriptions.',
  'Old city, near Khan al-Misriyye',
  34.4343,
  35.8355,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '30–45 mins',
  '',
  'Between prayer times',
  4.6,
  0,
  NULL,
  '["mosque","minaret","mamluk"]'::jsonb,
  encode(digest('al_attar_mosque', 'sha256'), 'hex')
),
(
  'taynal_mosque',
  'Taynal Mosque',
  'Outside the old city wall in Bab al-Raml, built by Mamluk prince Sayf al-Din Taynal al-Hajib on a demolished Crusader church. Fortress-like appearance; hidden passages in the walls; large dome on four Byzantine capitals over granite columns on a marble courtyard; minaret with twin stone staircases; celebrated wooden mihrab.',
  'Bab al-Raml neighbourhood',
  34.4325,
  35.8288,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '45 mins – 1 hour',
  '',
  'Morning',
  4.7,
  0,
  NULL,
  '["mosque","mamluk","dome","mihrab"]'::jsonb,
  encode(digest('taynal_mosque', 'sha256'), 'hex')
),
(
  'al_uwaysiya_mosque',
  'Al-Uwaysiya Mosque',
  'Began as a small Mamluk zawiya; later the Ottomans converted it to a mosque and added an Ottoman minaret. It has the largest dome among Tripoli’s medieval mosques. Linked to Sufi Sheikh Uwais al-Roumi. On the west bank of the Abou Ali, lane toward the fish market.',
  'Abou Ali River, west bank',
  34.4338,
  35.8339,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '30 mins',
  '',
  'Between prayer times',
  NULL,
  NULL,
  NULL,
  '["mosque","dome","sufi","ottoman"]'::jsonb,
  encode(digest('al_uwaysiya_mosque', 'sha256'), 'hex')
),
(
  'al_tahham_mosque',
  'Al-Tahham Mosque',
  'Mamluk-era mosque; builder unknown. Above shops in al-Haddadine, reached by stairs; small minaret but distinguished by granite columns with Corinthian capitals, carvings and ornament.',
  'Al-Haddadine quarter',
  34.4336,
  35.8349,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '20–30 mins',
  '',
  'Between prayer times',
  NULL,
  NULL,
  NULL,
  '["mosque","haddadine","mamluk"]'::jsonb,
  encode(digest('al_tahham_mosque', 'sha256'), 'hex')
),
(
  'al_muallaq_mosque',
  'Al-Muallaq Mosque (The Suspended Mosque)',
  'Built in 1555 by Mahmoud Lotfi al-Zaim (Ottoman era) above cellars and shops in al-Haddadine — hence “Suspended.” Also called Mahmudiyah. Octagonal minaret with eight arches and balconied circular floral motifs at the top.',
  'Al-Haddadine',
  34.4341,
  35.8351,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '30–45 mins',
  '',
  'Between prayer times',
  NULL,
  NULL,
  NULL,
  '["mosque","ottoman","suspended","minaret"]'::jsonb,
  encode(digest('al_muallaq_mosque', 'sha256'), 'hex')
),
(
  'al_hamdi_mosque',
  'Al-Hamdi Mosque (Tanners’ Mosque)',
  'Thought to date from the turn of the 16th century (late Mamluk Levant). Originally Mosque al-Tuffahi; also called al-Dabbaghin (tanners). Demolished and rebuilt in 1892 under Sultan Abdul Hamid II.',
  'Old city, Tripoli',
  34.4339,
  35.8352,
  NULL,
  '[]'::jsonb,
  'Historic mosques',
  'mosques',
  '20–30 mins',
  '',
  'Between prayer times',
  NULL,
  NULL,
  NULL,
  '["mosque","ottoman","tanners"]'::jsonb,
  encode(digest('al_hamdi_mosque', 'sha256'), 'hex')
),
(
  'al_mashhad_madrasa',
  'Al-Mashhad Madrasa',
  'Mamluk-era madrasa named for a shrine inside. Faces al-Shamsiya Madrasa in al-Nouri quarter, right of the Great Mansouri main entrance. Noted for mosaic and marble gate and Mamluk muqarnas.',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.434,
  35.8353,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_mashhad_madrasa', 'sha256'), 'hex')
),
(
  'al_nouriya_madrasa',
  'Al-Nouriya Madrasa',
  'Often dated to 1310 by Prince Sangar bin Abdullah al-Nouri, or attributed to a wealthy citizen or Prince Nour al-Din who also built Hammam al-Nouri opposite. Black-and-white striped Arabic portal; marble mihrab with mosaics among the finest in Tripoli.',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.4342,
  35.8355,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_nouriya_madrasa', 'sha256'), 'hex')
),
(
  'al_qartawiya_madrasa',
  'Al-Qartawiya Madrasa',
  'One of six schools around the Great Mansouri Mosque; among the largest Mamluk religious institutions. Ordered by Prince Sayf al-Din Qaratay (1316–1326). Rear wall with geometry, ornament and Quranic verses used to post public rulings; monumental muqarnas gate.',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.4339,
  35.8354,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_qartawiya_madrasa', 'sha256'), 'hex')
),
(
  'al_qadiriya_madrasa',
  'Al-Qadiriya Madrasa',
  '14th-century Mamluk madrasa; second largest after al-Qartawiya. Recently converted into a mosque. Plain gate; tomb of an unidentified person inside.',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.4338,
  35.8352,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_qadiriya_madrasa', 'sha256'), 'hex')
),
(
  'al_nasiriya_madrasa',
  'Al-Nasiriya Madrasa',
  'Mid-14th century, built by Sultan Hassan bin Muhammad bin Qalawun (al-Nasir). Left of the road to the Great Mansouri; inscription “Glory to Mawlana Sultan Nasir.”',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.43405,
  35.83545,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_nasiriya_madrasa', 'sha256'), 'hex')
),
(
  'al_saqraqiya_madrasa',
  'Al-Saqraqiya Madrasa',
  'Early 14th century by Sayf al-Din Aqraq. Facade inscriptions give founding date and endowed properties.',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.4337,
  35.8351,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_saqraqiya_madrasa', 'sha256'), 'hex')
),
(
  'al_khatouniya_madrasa',
  'Al-Khatouniya Madrasa',
  '1374, by Prince Izz al-Din Edmer al-Ashrafi and his wife Argoun Khatoun. Haddadine (Saff al-Blat), faces al-Saqraqiya. Prince’s blazon between windows; property laws carved on entry wall.',
  'Old city — near Great Mansouri / al-Nouri quarter',
  34.4335,
  35.835,
  NULL,
  '[]'::jsonb,
  'Madrasas',
  'madrasas',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["madrasa","mamluk","school"]'::jsonb,
  encode(digest('al_khatouniya_madrasa', 'sha256'), 'hex')
),
(
  'al_khanqah_tripoli',
  'Al-Khanqah',
  'Built in 1467 in al-Haddadine under Prince Qaynay al-Mu’ayyadi. Named for Sitt Salha (“Khanqah”). Sufis, warriors and visitors lodged here for worship and city defence. Large gate, narrow passage, courtyard with a calm central pool.',
  'Al-Haddadine',
  34.4336,
  35.83495,
  NULL,
  '[]'::jsonb,
  'Khanqahs & takiyas',
  'khanqahs_takiyas',
  '30 mins',
  '',
  'By arrangement',
  NULL,
  NULL,
  NULL,
  '["khanqah","sufi","mamluk"]'::jsonb,
  encode(digest('al_khanqah_tripoli', 'sha256'), 'hex')
),
(
  'takiya_al_mawlawiya',
  'Al-Takiya al-Mawlawiya',
  'One of seven Ottoman Mawlawi takiyas outside Turkey (with Cairo, Jerusalem, Damascus, Aleppo, Bosnia, Cyprus). Built 1619 by Samsunji Ali for Mawlawi dervishes of Jalaluddin Rumi’s order. Served worship and teaching until the mid-20th century.',
  'Tripoli',
  34.4348,
  35.8362,
  NULL,
  '[]'::jsonb,
  'Khanqahs & takiyas',
  'khanqahs_takiyas',
  '30–45 mins',
  '',
  'Check access',
  NULL,
  NULL,
  NULL,
  '["takiya","mawlawi","ottoman","sufi"]'::jsonb,
  encode(digest('takiya_al_mawlawiya', 'sha256'), 'hex')
),
(
  'souk_haraj',
  'Souk Haraj',
  'Crusader-era monumental hall with crossing vaults on two large granite columns, possibly reusing a church or Roman temple. Under the Mamluks converted to a khan: upper floor for merchants, ground for trade and animals.',
  'Old city markets',
  34.4345,
  35.8358,
  NULL,
  '[]'::jsonb,
  'Khans (caravanserais)',
  'khans',
  '30–45 mins',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["souk","khan","vault","crusader"]'::jsonb,
  encode(digest('souk_haraj', 'sha256'), 'hex')
),
(
  'khan_al_askar',
  'Khan al-Askar',
  'After fire destroyed the Saint-Gilles citadel, the Mamluks built this instead of barracks there. Two long rectangular blocks with a central stable for horses; about 400 m²; used through Ottoman and French periods.',
  'Old city',
  34.4335,
  35.8347,
  NULL,
  '[]'::jsonb,
  'Khans (caravanserais)',
  'khans',
  '45 mins – 1 hour',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["khan","mamluk","military"]'::jsonb,
  encode(digest('khan_al_askar', 'sha256'), 'hex')
),
(
  'khan_al_khayyatin',
  'Khan al-Khayyatin (Tailors’ Khan)',
  'Long rectangular plan: ground floor like a street of workshops; upper rooms under a series of ten arches. East and west entrances; western gate has a column with Roman Corinthian capital. Often dated stylistically to the 17th century and later Ottoman context in guides.',
  'Old city souks',
  34.4333,
  35.8333,
  NULL,
  '[]'::jsonb,
  'Khans (caravanserais)',
  'khans',
  '1 hour',
  '',
  'Morning to afternoon',
  NULL,
  NULL,
  NULL,
  '["khan","tailors","textiles","souk"]'::jsonb,
  encode(digest('khan_al_khayyatin', 'sha256'), 'hex')
),
(
  'khan_al_saboun',
  'Khan al-Saboun',
  'Built 1480 under governor Youssef Bey Sifa; first as military barracks, then as a khan. Centre of Tripoli soap production and trade; still noted for its tall original wooden gate with side windows for guards to watch the entrance.',
  'Old city, near clock tower area',
  34.4336,
  35.8344,
  NULL,
  '[]'::jsonb,
  'Khans (caravanserais)',
  'khans',
  '45 mins – 1 hour',
  '',
  'Daytime',
  NULL,
  NULL,
  NULL,
  '["khan","soap","ottoman","craft"]'::jsonb,
  encode(digest('khan_al_saboun', 'sha256'), 'hex')
),
(
  'hammam_izz_ed_dine',
  'Hammam Izz Ed-Dine',
  'Among Tripoli’s oldest baths, near Khan al-Khayyatin. Prince Izz Ed-Dine Aybak al-Mawsili built it in 1294 on Crusader foundations; architecture parallels the khan. Floor later paved with Carrara marble; new entry to Nahhasin market side c. late 19th century. Entry carved with Lamb of God and a Crusader inscription.',
  'Near Khan al-Khayyatin',
  34.43325,
  35.83335,
  NULL,
  '[]'::jsonb,
  'Hammams',
  'hammams',
  '45 mins',
  '',
  'Traditional hours',
  NULL,
  NULL,
  NULL,
  '["hammam","mamluk","bath"]'::jsonb,
  encode(digest('hammam_izz_ed_dine', 'sha256'), 'hex')
),
(
  'hammam_al_nouri',
  'Hammam al-Nouri',
  'In the al-Nouri area near the Great Mansouri and several madrasas. Attributed to Prince Sinjir bin Abdullah al-Nouri or Nour al-Din; early 8th century AH with the facing madrasa.',
  'Al-Nouri quarter',
  34.43415,
  35.8355,
  NULL,
  '[]'::jsonb,
  'Hammams',
  'hammams',
  '45 mins',
  '',
  'Check opening',
  NULL,
  NULL,
  NULL,
  '["hammam","mamluk"]'::jsonb,
  encode(digest('hammam_al_nouri', 'sha256'), 'hex')
),
(
  'hammam_al_abed',
  'Hammam al-Abed',
  'Tripoli’s only working historic hammam today. Probably mid-17th century Ottoman. Name linked to tradition of a murdered African servant at the door. Central hall under a large dome with pool and terraces; warm and hot rooms with steam and showers.',
  'Old city',
  34.4344,
  35.8358,
  NULL,
  '[]'::jsonb,
  'Hammams',
  'hammams',
  '1–2 hours',
  '',
  'Afternoon or evening',
  NULL,
  NULL,
  NULL,
  '["hammam","bath","operational"]'::jsonb,
  encode(digest('hammam_al_abed', 'sha256'), 'hex')
),
(
  'hammam_al_jadid',
  'Hammam al-Jadid',
  'Built 1740 by Asaad Pasha al-Azem — “the new hammam” beside older Mamluk and early Ottoman baths. Ornate gate, marble hall, large dome, central pond and fountain. Famous single-stone carved 14-link chain and bucket at the entrance.',
  'Old city',
  34.4342,
  35.836,
  NULL,
  '[]'::jsonb,
  'Hammams',
  'hammams',
  '1 hour',
  '',
  'By arrangement',
  NULL,
  NULL,
  NULL,
  '["hammam","ottoman","architecture"]'::jsonb,
  encode(digest('hammam_al_jadid', 'sha256'), 'hex')
),
(
  'tripoli_old_markets_network',
  'Tripoli old markets',
  'Among the world’s few ancient market networks still serving their original purpose. Some lines of trade go back eight centuries. Each souk took its name from its craft; the web runs from the east bank of the Abou Ali to Haddadine Gate — goldsmiths, herbs, shoes and more.',
  'Old city — river to Haddadine',
  34.4346,
  35.8364,
  NULL,
  '[]'::jsonb,
  'Historic markets',
  'old_markets',
  '2–3 hours',
  '',
  'Morning',
  NULL,
  NULL,
  NULL,
  '["souk","market","shopping","heritage"]'::jsonb,
  encode(digest('tripoli_old_markets_network', 'sha256'), 'hex')
),
(
  'shrine_our_lady_yunis',
  'Greek Orthodox shrine of Our Lady of Yunis',
  'Legend: a Yunishid man spared by the Virgin at this chapel; shrine marks the apparition. Popular with Christian visitors; old city. Latin inscription indicates Crusader-era origins.',
  'Old city',
  34.435,
  35.8368,
  NULL,
  '[]'::jsonb,
  'Churches & shrines',
  'churches',
  '20–30 mins',
  '',
  'Daylight',
  NULL,
  NULL,
  NULL,
  '["church","shrine","crusader","orthodox"]'::jsonb,
  encode(digest('shrine_our_lady_yunis', 'sha256'), 'hex')
),
(
  'st_george_greek_orthodox_cathedral',
  'St George Greek Orthodox Cathedral',
  'Largest historic church in Tripoli; Dabbagha area near Churches Street. Built from 1863 over ten years; inscription names builder Sophrianos. Rich icons, inscriptions and decoration.',
  'Dabbagha — Churches Street',
  34.4352,
  35.8365,
  NULL,
  '[]'::jsonb,
  'Churches & shrines',
  'churches',
  '30–45 mins',
  '',
  'Services or visits by arrangement',
  NULL,
  NULL,
  NULL,
  '["cathedral","orthodox","19th century"]'::jsonb,
  encode(digest('st_george_greek_orthodox_cathedral', 'sha256'), 'hex')
),
(
  'st_nicholas_greek_orthodox_church',
  'St Nicholas Greek Orthodox Church',
  'Early 19th century: Muslims and Orthodox agreed to replace a church near al-Uwaysiyat (lost to a factory in Tarbiah). New church in Levantine style — rectangular, no domes; four apses and four naves. Museum icons from the old building.',
  'Old city',
  34.4339,
  35.8341,
  NULL,
  '[]'::jsonb,
  'Churches & shrines',
  'churches',
  '30 mins',
  '',
  'By arrangement',
  NULL,
  NULL,
  NULL,
  '["orthodox","church"]'::jsonb,
  encode(digest('st_nicholas_greek_orthodox_church', 'sha256'), 'hex')
),
(
  'st_joseph_syriac_catholic_church',
  'St Joseph Syriac Catholic Church',
  'Originally a 19th-century Franciscan church beside St George Greek Orthodox Cathedral.',
  'Near St George Cathedral',
  34.43522,
  35.83652,
  NULL,
  '[]'::jsonb,
  'Churches & shrines',
  'churches',
  '20 mins',
  '',
  'By arrangement',
  NULL,
  NULL,
  NULL,
  '["syriac","catholic","church"]'::jsonb,
  encode(digest('st_joseph_syriac_catholic_church', 'sha256'), 'hex')
),
(
  'st_michael_maronite_church',
  'St Michael Maronite Church',
  'Large Western-style cathedral; inscription over door gives 1858.',
  'Tripoli',
  34.4349,
  35.8372,
  NULL,
  '[]'::jsonb,
  'Churches & shrines',
  'churches',
  '30 mins',
  '',
  'By arrangement',
  NULL,
  NULL,
  NULL,
  '["maronite","church"]'::jsonb,
  encode(digest('st_michael_maronite_church', 'sha256'), 'hex')
),
(
  'el_mina_train_station',
  'El-Mina train station',
  'Around 1900 the first train reached El-Mina; the station was paid for by Tripoli residents and linked the city to Istanbul and cities such as Paris on the Orient Express network. Remaining structures act as a kind of museum awaiting restoration; rolling stock includes German 1985 and French 1985 and 1901 sets on site per local inventory.',
  'El-Mina',
  34.451,
  35.808,
  NULL,
  '[]'::jsonb,
  'Modern Tripoli landmarks',
  'modern_heritage',
  '30–45 mins',
  '',
  'Daylight',
  NULL,
  NULL,
  NULL,
  '["train","station","heritage","mina"]'::jsonb,
  encode(digest('el_mina_train_station', 'sha256'), 'hex')
),
(
  'al_hamidiya_clock',
  'Al-Hamidiya clock tower',
  'Ottoman clock built 1901 for the 25th anniversary of Sultan Abdul Hamid II’s accession; centre of Al-Tal square. Built before the Ottoman Saray (1890, demolished 1960s). Five levels with internal spiral iron stair.',
  'Al-Tal square',
  34.4361,
  35.8383,
  NULL,
  '[]'::jsonb,
  'Modern Tripoli landmarks',
  'modern_heritage',
  '15–20 mins',
  '',
  'Any time',
  NULL,
  NULL,
  NULL,
  '["clock","ottoman","tal","landmark"]'::jsonb,
  encode(digest('al_hamidiya_clock', 'sha256'), 'hex')
),
(
  'al_tal_square',
  'Al-Tal square',
  'Late 19th-century hub of modern Tripoli outside the Mamluk core. Ottoman and European-style buildings — banks, cafés, hotels, parks, villas and former government seats including the demolished Ottoman Seray. Many structures neglected but evocative of the modern city’s past.',
  'Al-Tal, Tripoli',
  34.4363,
  35.8385,
  NULL,
  '[]'::jsonb,
  'Modern Tripoli landmarks',
  'modern_heritage',
  '1 hour',
  '',
  'Evening stroll',
  NULL,
  NULL,
  NULL,
  '["square","ottoman","urban","tal"]'::jsonb,
  encode(digest('al_tal_square', 'sha256'), 'hex')
),
(
  'rashid_karami_international_fair',
  'Rashid Karami International Fair',
  'Conceived in the late 1950s; built 1964–1975 from 1960s designs. Brazilian architect Oscar Niemeyer master-planned roughly one million square metres — a landmark of modern architecture.',
  'Tripoli fairgrounds',
  34.421,
  35.872,
  NULL,
  '[]'::jsonb,
  'Nature & major sites',
  'natural_urban',
  '1–2 hours',
  '',
  'Daytime events or exterior visit',
  NULL,
  NULL,
  NULL,
  '["fair","niemeyer","architecture","modern"]'::jsonb,
  encode(digest('rashid_karami_international_fair', 'sha256'), 'hex')
),
(
  'palm_islands_nature_reserve',
  'Palm Islands Nature Reserve',
  'Three uninhabited islands off El-Mina; named for large palms on one island — also called Rabbits Island (Araneb). Islands: Rabbits (largest), al-Sanani, al-Fanar (Ramkine).',
  'Off El-Mina coast',
  34.542,
  35.785,
  NULL,
  '[]'::jsonb,
  'Nature & major sites',
  'natural_urban',
  'Half day (boat)',
  '',
  'Calm weather',
  NULL,
  NULL,
  NULL,
  '["island","nature","reserve","sea","mina"]'::jsonb,
  encode(digest('palm_islands_nature_reserve', 'sha256'), 'hex')
),
(
  'abou_ali_river',
  'Abou Ali River',
  '20th-century floods damaged historic riverfront architecture; widening the bed changed Tripoli’s old landscape. Before that, the river inspired European painters and travellers as the classic eastern city waterfront. The expansion and floods permanently altered the banks.',
  'Through Tripoli',
  34.4389,
  35.84,
  NULL,
  '[]'::jsonb,
  'Nature & major sites',
  'natural_urban',
  'Walking along embankments',
  '',
  'Morning or evening',
  NULL,
  NULL,
  NULL,
  '["river","waterfront","urban"]'::jsonb,
  encode(digest('abou_ali_river', 'sha256'), 'hex')
),
(
  'tripolitan_cuisine',
  'Tripolitan cuisine',
  'Tripoli’s traditional food is rich and varied — especially sweets: the city is known for dozens of kinds of oriental pastries and desserts, plus beloved everyday dishes and drinks.',
  'Citywide',
  34.435,
  35.836,
  NULL,
  '[]'::jsonb,
  'Cuisine & crafts',
  'living_heritage',
  'Varies',
  '',
  'Markets and sweet shops — daytime',
  NULL,
  NULL,
  NULL,
  '["food","sweets","cuisine","culture"]'::jsonb,
  encode(digest('tripolitan_cuisine', 'sha256'), 'hex')
),
(
  'artisanal_crafts_tripoli',
  'Artisanal crafts of Tripoli',
  'Tripoli is known for fine traditional handicrafts. Older masters still try to teach youth, though many trades are endangered or extinct; advocates call for stronger celebration of this heritage.',
  'Souks and workshops — old city',
  34.4344,
  35.8358,
  NULL,
  '[]'::jsonb,
  'Cuisine & crafts',
  'living_heritage',
  '1–2 hours',
  '',
  'Morning workshops',
  NULL,
  NULL,
  NULL,
  '["craft","handicraft","heritage","souk"]'::jsonb,
  encode(digest('artisanal_crafts_tripoli', 'sha256'), 'hex')
);
